### ISSUE TITLE
Create or fix unit test suite for all NApps

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#796]
napp_name: unit test coverage

- [x] [mef_eline](https://github.com/kytos/mef_eline): 62%
- [x] [topology](https://github.com/kytos/topology): 17%
- [x] [pathfinder](https://github.com/kytos/pathfinder): 0%
- [x] [flow_manager](https://github.com/kytos/flow_manager): 0%
- [x] [of_core](https://github.com/kytos/of_core): 28%
- [x] [of_l2ls](https://github.com/kytos/of_l2ls): 0%
- [x] [of_lldp](https://github.com/kytos/of_lldp): 0%
- [ ] [of_stats](https://github.com/kytos/of_stats)
- [x] [status](https://github.com/kytos/status): 7%
- [x] [storehouse](https://github.com/kytos/storehouse): 0%

**Comment by hdiogenes** [comment]
This is related to [797: Configure scrutinizer in all NApps](https://github.com/kytos/kytos/issues/797).

**Comment by beraldoleal** [comment]
@macartur can you please check which NApps have tests?

**Comment by hdiogenes** [comment]
For everyone who's having problems with napp unit tests, please try copying these files from my topology branch and running tests with `tox`:

* https://github.com/hdiogenes/topology/blob/fix-unit-tests/setup.py
* https://github.com/hdiogenes/topology/blob/fix-unit-tests/tox.ini

**Comment by hdiogenes** [comment]
Also, we now have a global `Kytos NApp` Scrutinizer config, so need to remove the local `.scrutinizer.yml` from all NApps.
