### ISSUE TITLE
Add all NApps to Scrutinizer

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#797]
- [x] [mef_eline](https://scrutinizer-ci.com/g/kytos/mef_eline)
- [x] [topology](https://scrutinizer-ci.com/g/kytos/topology)
- [x] [pathfinder](https://scrutinizer-ci.com/g/kytos/pathfinder)
- [x] [flow_manager](https://scrutinizer-ci.com/g/kytos/flow_manager)
- [x] [of_core](https://scrutinizer-ci.com/g/kytos/of_core)
- [x] [of_l2ls](https://scrutinizer-ci.com/g/kytos/of_l2ls)
- [x] [of_lldp](https://scrutinizer-ci.com/g/kytos/of_lldp)
- [x] [of_stats](https://scrutinizer-ci.com/g/kytos/of_stats)
- [x] [status](https://scrutinizer-ci.com/g/kytos/status)
- [x] [storehouse](https://scrutinizer-ci.com/g/kytos/storehouse)

**Comment by hdiogenes** [comment]
Done for `mef_eline` on PR https://github.com/kytos/mef_eline/pull/65

**Comment by beraldoleal** [comment]
@macartur we just realized that this napps are enabled on your account or somebody else account. So I created an "organization" kytos on scrutinizer.. You and @hdiogenes are admins now. All NApps and repo must be migrated to there.

**Comment by hdiogenes** [comment]
Just added `of_core` to Scrutinizer.

**Comment by hdiogenes** [comment]
NApp `topology` was added to Scrutinizer with new `setup.py` and `tox.ini` from `of_core`, and the new `Kytos NApp` Scrutinizer configuration.

**Comment by hdiogenes** [comment]
For everyone who's having problems with napp unit tests, please try copying these files from my topology branch and running tests with `tox`:
 * https://github.com/hdiogenes/topology/blob/fix-unit-tests/setup.py
 * https://github.com/hdiogenes/topology/blob/fix-unit-tests/tox.ini

**Comment by hdiogenes** [comment]
All the NApps were added to Scrutinizer. We're still having some problems with unit tests, but that will be fixed in a separate issue: #796.
